name: Auto Approve
description: Auto-approve pull requests based on configurable conditions
author: shunkakinoki
branding:
  icon: check-circle
  color: green
inputs:
  github-token:
    description: GitHub token for API access
    required: true
runs:
  using: composite
  steps:
    - name: Auto Approve PR
      uses: hmarr/auto-approve-action@v4
      with:
        github-token: ${{ inputs.github-token }}
