name: Setup Bun
description: Setup Bun, install dependencies, and optionally run bun install with caching
author: shunkakinoki
branding:
  icon: code
  color: purple
inputs:
  bun-version:
    description: Bun version to use (e.g., '1.0.0')
    required: false
    default: ''
  install-dependencies:
    description: Run 'bun install' after setup
    required: false
    default: 'true'
  working-directory:
    description: Working directory to run bun install in
    required: false
    default: ''
  enable-turbo-cache:
    description: Enable Turbo caching for the repository
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}
    - name: Cache for Turbo
      if: inputs.enable-turbo-cache == 'true'
      uses: rharkor/caching-for-turbo@v2.2.1
      with:
        cache-prefix: turbo-
    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        if [ -n "${{ inputs.working-directory }}" ]; then
          cd "${{ inputs.working-directory }}"
        fi
        bun install
