name: Auto Merge
description: Auto-merge pull requests based on configurable conditions
author: shunkakinoki
branding:
  icon: git-merge
  color: purple
inputs:
  github-token:
    description: GitHub token with merge permissions (PAT recommended)
    required: true
runs:
  using: composite
  steps:
    - name: Auto Merge PR
      shell: bash
      run: |
        gh pr merge ${{ github.event.pull_request.number }} --auto --${{ inputs.merge-method }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
