name: Changesets
description: Run Changesets commands with Bun and optional auth
author: shunkakinoki
branding:
  icon: package
  color: blue
inputs:
  github-token:
    description: GitHub token used by Changesets for creating PRs
    required: true
  npm-token:
    description: NPM token for publishing
    required: false
    default: ''
  publish-command:
    description: Command to run for publishing
    required: false
    default: 'bun run publish'
  version-command:
    description: Command to run for versioning
    required: false
    default: 'bun run version'
  create-github-releases:
    description: Create GitHub releases after publish (tags + releases)
    required: false
    default: 'true'
  commit-mode:
    description: Commit mode to push changes and tags (git-cli or github-api)
    required: false
    default: 'git-cli'
  validate-pull-request:
    description: Validate pull request by checking changeset status
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Fetch base branch
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        git fetch --no-tags --prune origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
    - name: Validate Changesets
      if: inputs.validate-pull-request == 'true' && github.event_name == 'pull_request'
      shell: bash
      run: |
        output=$(bunx changeset status --verbose 2>&1)
        status=$?
        if echo "$output" | grep -q "No changesets found"; then
          echo "No changesets found, ignoring error."
        elif [ "$status" -ne 0 ]; then
          echo "Changeset status failed with exit code $status"
          echo "$output"
          exit $status
        fi
    - name: Export environment variables
      shell: bash
      run: |
        echo "GITHUB_SHA=${{ github.sha }}" >> $GITHUB_ENV
        echo "GITHUB_REF=${{ github.ref }}" >> $GITHUB_ENV
        echo "GITHUB_HEAD_REF=${{ github.head_ref }}" >> $GITHUB_ENV
        echo "GITHUB_BASE_REF=${{ github.base_ref }}" >> $GITHUB_ENV
        echo "GITHUB_EVENT_NAME=${{ github.event_name }}" >> $GITHUB_ENV
        echo "GITHUB_EVENT_PATH=${{ github.event_path }}" >> $GITHUB_ENV
        echo "GITHUB_EVENT_NUMBER=${{ github.event_number }}" >> $GITHUB_ENV
        echo "GITHUB_REF_NAME=${{ github.ref_name }}" >> $GITHUB_ENV
      env:
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        GITHUB_EVENT_NAME: ${{ github.event_name }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        GITHUB_EVENT_NUMBER: ${{ github.event_number }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
    - name: Run Changesets (official)
      uses: changesets/action@v1
      with:
        publish: ${{ inputs.publish-command }}
        version: ${{ inputs.version-command }}
        createGithubReleases: ${{ inputs.create-github-releases }}
        commitMode: ${{ inputs.commit-mode }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
        NPM_CONFIG_TOKEN: ${{ inputs.npm-token }}
