name: Changesets
description: Run official Changesets action with Bun setup
author: shunkakinoki
branding:
  icon: package
  color: blue
inputs:
  github-token:
    description: GitHub token used by Changesets for creating PRs
    required: true
  bun-version:
    description: Bun version to use
    required: false
    default: ''
  npm-token:
    description: NPM token for publishing
    required: false
    default: ''
  version-command:
    description: Command to run for versioning
    required: false
    default: 'bun run version'
  publish-command:
    description: Command to run for publishing
    required: false
    default: 'bun run release'
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: ./.github/actions/setup-bun
      with:
        bun-version: ${{ inputs.bun-version }}
        install-dependencies: 'true'
    - name: Run Changesets (official)
      uses: changesets/action@v1
      with:
        version: ${{ inputs.version-command }}
        publish: ${{ inputs.publish-command }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
