name: Changesets
description: Run Changesets commands with Bun and optional auth
author: shunkakinoki
branding:
  icon: package
  color: blue
inputs:
  github-token:
    description: GitHub token used by Changesets for creating PRs
    required: true
  npm-token:
    description: NPM token for publishing
    required: false
    default: ''
  publish-command:
    description: Command to run for publishing
    required: false
    default: 'bun run release'
  create-github-releases:
    description: Create GitHub releases after publish (tags + releases)
    required: false
    default: 'true'
  commit-mode:
    description: Commit mode to push changes and tags (git-cli or github-api)
    required: false
    default: 'git-cli'
  validate-pull-request:
    description: Validate pull request by checking changeset status
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Fetch base branch
      if: github.event_name == 'pull_request'
      shell: bash
      run: |
        git fetch --no-tags --prune origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}
    - name: Validate Changesets
      if: inputs.validate-pull-request == 'true' && github.event_name == 'pull_request'
      shell: bash
      run: |
        output=$(bunx changeset status 2>&1)
        status=$?
        if echo "$output" | grep -q "No changesets found"; then
          echo "No changesets found, ignoring error."
        elif [ "$status" -ne 0 ]; then
          echo "Changeset status failed with exit code $status"
          echo "$output"
          exit $status
        fi
    - name: Run Changesets (official)
      uses: changesets/action@v1
      with:
        publish: ${{ inputs.publish-command }}
        createGithubReleases: ${{ inputs.create-github-releases }}
        commitMode: ${{ inputs.commit-mode }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        NPM_TOKEN: ${{ inputs.npm-token }}
